development:
  adapter: postgresql
  encoding: utf8
  database: casenexus_development
  pool: 5
  username: user1
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: casenexus_test
  pool: 5
  username: user1
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: casenexus
  pool: 5
  username: user1
  password: