
desc "Books Update 2 - 26th November 2013"

task :books_update_2 => :environment do

  puts "Adding Michigan university"
  University.create!(name: "UMich", image: "umich.png", domain: "umich.edu", enabled: false)

  puts "Running book update 2"

  # Michigan 2007
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_1.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "2", title: "Business School Journal", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "Your client is a European academic institution that wants to increase the brand profile of their business school. One strategy that they have identified is creating a business journal. The university has done its own research, but has also asked you to do a pro bono assessment of this strategy. They want to know if the strategy will increase their brand image, and also if it will be profitable.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_2.pdf", thumb: "michigan.png", university_id: "19", chart_num: "3", difficulty: "2", title: "Bottle Shifters", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "“Bottle Shifters” design and distribute bottles. Its customers are small/medium sized companies (in the food/drinks sector e.g. startup /brewery). It is the biggest 3rd party manufacturer in the industry.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_3.pdf", thumb: "michigan.png", university_id: "19", chart_num: "4", difficulty: "2", title: "Retirement Plan", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "The client is a large international asset management firm, FinCo, looking the enter the use market for retirement plans. FinCo trying to decide whether to provide IRAs or Defined Contribution plans. Today both markets are the same size (~ $3 Trillion), and both generate the same fees. FinCo is interested in knowing the five year growth outlook for each of these markets.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_4.pdf", thumb: "michigan.png", university_id: "19", chart_num: "2", difficulty: "2", title: "Airplane De-Icing", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "Your client is AirCo, a U.S. airline that has significant operations at one Chicago airport.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_5.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "2", title: "Deposit Slips", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "Your client manufactures and sells deposit slips to banks at a price of $1/slip. They are the leading firm in this $100Mn industry with 60% market share. There is only one other competitor.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_6.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "2", title: "CPG Profit", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "A CPG company with national presence has declining profits. The company has hammered on the cost side of its operations, yet profits are still declining. The company has hired BAH to help.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_7.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "2", title: "Petrochemical Spin Off", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "A commodity petrochemical division has spun off from a major oil company. The new company called ITG group of BAH to look into IT issues and suggest ways to optimize IT expenses.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_8.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "2", title: "PCB Manufacturer", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "Our client is a firm who wants to invest in a Printed Circuit Board (PCB) manufacturer. The client wants to know whether it’s going to be a good investment.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_9.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "2", title: "Home Garden Chemicals", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "Our Client is a home garden chemicals manufacturer. Its product lines include herbicides and manure. Annual revenue is $1Bn.") 
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_10.pdf", thumb: "michigan.png", university_id: "19", chart_num: "1", difficulty: "2", title: "Gardening Retailer", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "You have been approached by the COO of a $2B Midwest Industrial Company who makes fertilizers, pesticides etc. for lawn and garden.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_11.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "2", title: "Pipeline Manufacturer", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "The client is a pipeline manufacturer. They think about entering the US market and hired you to advise whether they should do that, and if so, how to enter.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_12.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "2", title: "Tobacco Leaf Processor", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "Tobacco is a commodity and revenues in the tobacco industry are flat.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_13.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "3", title: "Incinerator", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "The client is a waste management company in Italy.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_14.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "2", title: "German Luxury Car Maker", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "A German luxury car maker wants to grow business and is looking into selling cars in Bangladesh. The GDP growth in Bangladesh is 5% per year. Currently, the only luxury car sold in Bangladesh is Mercedes-Benz and they have been in the market for the past 10 years.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_15.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "2", title: "Hotel Franchisor", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "You have been hired by the CEO of a Hotel Franchise. Yearly revenues have been stagnant at $600MM while the competition has been growing. The CEO wants to know why this is and what can be done.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_16.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "3", title: "Pharmaceutical Pricing", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "Your client is a pharmaceutical firm that has developed an AIDS drug. They have already created a plan to role the drug out to the developed world (e.g., U.S., Europe, Japan), but have not yet developed a roll-out plan for the developing world, which nations that range from extremely poor, such as sub- Saharan Africa, to nations that are close to developed, such as Eastern Europe. The client wants to know how it should price this drug for the developing world.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_17.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "2", title: "Diabetes Testing Meter", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "Our client is a laboratory that provides diabetes testing services to hospitals in UK. They have developed a self-diagnosis meter that patients can use to do testing on their own. They have hired us to determine if we should take this product to the market.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_18.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "2", title: "Drug Store Profitability", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "Our client is a drug store chain, similar to CVS, They are losing profits in the last few years. Can you help us identify the reasons and means to improve the profits.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_19.pdf", thumb: "michigan.png", university_id: "19", chart_num: "0", difficulty: "3", title: "Direct Mail Campaign", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "Our client is a telecom fortune 50 company. One of its divisions (landline) is facing high churn (3% per yr). They have launched a direct mail campaign targeting their customers who have switched to other telecom service providers.")
  Book.create!(btype: "case", tag_list: [""], url: "michigan_2007_20.pdf", thumb: "michigan.png", university_id: "19", chart_num: "4", difficulty: "2", title: "Cleaning Supplies", source_title: "Consulting Case Interview Preparation Guide 2009-2010", author: "Ross School of Business Consulting Club", author_url: "http://www.bus.umich.edu/", desc: "Your client is a Cleaning Supplies Manufacturer. They are trying to redesign their Sales Force and have approached you for advice.")


  puts "Done."
end


